server:
  port: 8201
  
spring:
  application:
    name: FEBS-Server-System
    
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20 #向Eureka 服务端发送心跳的间隔时间，单位为秒，用于服务续约。这里配置为20秒，即每隔20秒向febs-register发送心跳，表明当前服务没有宕机
  client:
    register-with-eureka: true ##为true时表示将当前服务注册到Eureak服务端
    fetch-registry: true ##为true时表示从Eureka 服务端获取注册的服务信息
    instance-info-replication-interval-seconds: 30 #新实例信息的变化到Eureka服务端的间隔时间，单位为秒
    serviceUrl:
      defaultZone: http://febs:123456@localhost:8001/register/eureka/ #指定Eureka服务端地址
      
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8301/auth/user  #通过微服务网关，该请求将被转发到http://localhost:8101/user。该配置的作用主要有两个：
                                                                                                                 # 1、到认证服务器里校验当前请求头中的令牌是否为合法的令牌；
                                                                                                                 # 2、通过当前令牌获取对应的用户信息。